//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neuronic.TimeFrequency.Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neuronic.TimeFrequency.Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.24053203e-10,  1.81899706e-10,  2.65884545e-10,  3.87427851e-10,
        ///5.62762029e-10,  8.14881546e-10,  1.17624952e-09,  1.69254117e-09,
        ///2.42780238e-09,  3.47153250e-09,  4.94837305e-09,  7.03131242e-09,
        ///9.95961568e-09,  1.40630795e-08,  1.97947208e-08,  2.77746655e-08,
        ///3.88488529e-08,  5.41672581e-08,  7.52877223e-08,  1.04313247e-07,
        ///1.44072835e-07,  1.98358758e-07,  2.72236648e-07,  3.72449161e-07,
        ///5.07939354e-07,  6.90526586e-07,  9.35775844e-07,  1.26411132e-06,
        ///1.70223704e-06,  2.28494160e-06,  3. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_gaus1 {
            get {
                return ResourceManager.GetString("wavefun_gaus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -7.01897073e-10, -1.02079158e-09, -1.47981439e-09, -2.13837049e-09,
        ///-3.08008844e-09, -4.42228694e-09, -6.32897073e-09, -9.02860395e-09,
        ///-1.28383244e-08, -1.81968062e-08, -2.57086866e-08, -3.62043948e-08,
        ///-5.08204057e-08, -7.11064688e-08, -9.91683126e-08, -1.37856803e-07,
        ///-1.91017672e-07, -2.63819879e-07, -3.63185603e-07, -4.98351007e-07,
        ///-6.81594515e-07, -9.29178682e-07, -1.26256316e-06, -1.70996012e-06,
        ///-2.30832023e-06, -3.10585729e-06, -4.16524344e-06, -5.56763515e-06,
        ///-7.41772273e-06, -9.85003485e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_gaus2 {
            get {
                return ResourceManager.GetString("wavefun_gaus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -3.01085754e-09, -4.34144868e-09, -6.23951610e-09, -8.93793604e-09,
        ///-1.27612126e-08, -1.81598911e-08, -2.57572385e-08, -3.64123110e-08,
        ///-5.13048158e-08, -7.20488368e-08, -1.00844614e-07, -1.40680277e-07,
        ///-1.95598857e-07, -2.71050205e-07, -3.74352877e-07, -5.15297712e-07,
        ///-7.06933197e-07, -9.66582879e-07, -1.31715757e-06, -1.78884017e-06,
        ///-2.42123915e-06, -3.26612832e-06, -4.39091643e-06, -5.88302006e-06,
        ///-7.85534852e-06, -1.04531499e-05, -1.38625137e-05, -1.83208765e-05,
        ///-2.41299365e-05, -3.16714437e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_gaus3 {
            get {
                return ResourceManager.GetString("wavefun_gaus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.06681183e-08,  1.52451629e-08,  2.17124166e-08,  3.08186435e-08,
        ///4.35958827e-08,  6.14612353e-08,  8.63531353e-08,  1.20913008e-07,
        ///1.68726388e-07,  2.34641558e-07,  3.25188795e-07,  4.49129502e-07,
        ///6.18172259e-07,  8.47902239e-07,  1.15898199e-06,  1.57869558e-06,
        ///2.14292473e-06,  2.89866571e-06,  3.90721904e-06,  5.24821173e-06,
        ///7.02464333e-06,  9.36918356e-06,  1.24519899e-05,  1.64903592e-05,
        ///2.17605764e-05,  2.86123782e-05,  3.74865015e-05,  4.89358472e-05,
        ///6.36508400e-05,  8.24896165e-05,  1. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_gaus4 {
            get {
                return ResourceManager.GetString("wavefun_gaus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.25257351e-08,  4.60428744e-08,  6.49505911e-08,  9.13030705e-08,
        ///1.27898469e-07,  1.78533186e-07,  2.48337338e-07,  3.44215331e-07,
        ///4.75421720e-07,  6.54310347e-07,  8.97304153e-07,  1.22614452e-06,
        ///1.66949269e-06,  2.26497194e-06,  3.06175851e-06,  4.12385102e-06,
        ///5.53417393e-06,  7.39969919e-06,  9.85780212e-06,  1.30841028e-05,
        ///1.73020820e-05,  2.27947985e-05,  2.99190764e-05,  3.91225655e-05,
        ///5.09641127e-05,  6.61379084e-05,  8.55018838e-05,  1.10110832e-04,
        ///1.41254698e-04,  1.80502426e-04,  2. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_gaus5 {
            get {
                return ResourceManager.GetString("wavefun_gaus5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -6.91988742e-13, -1.12277873e-12, -1.81435638e-12, -2.92000322e-12,
        ///-4.68031839e-12, -7.47132786e-12, -1.18781687e-11, -1.88074286e-11,
        ///-2.96576342e-11, -4.65767972e-11, -7.28496762e-11, -1.13477390e-10,
        ///-1.76040887e-10, -2.71981278e-10, -4.18489381e-10, -6.41281230e-10,
        ///-9.78655663e-10, -1.48739803e-09, -2.25132897e-09, -3.39362387e-09,
        ///-5.09448066e-09, -7.61633480e-09, -1.13396699e-08, -1.68136270e-08,
        ///-2.48271744e-08, -3.65086937e-08, -5.34646309e-08, -7.79715632e-08,
        ///-1.13240908e-07, -1.63781882e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_mexh {
            get {
                return ResourceManager.GetString("wavefun_mexh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -8.44621402e-15, -8.44451069e-15, -3.51327382e-15,  1.17518329e-14,
        ///4.57902859e-14,  1.10299978e-13,  2.19073416e-13,  3.83962177e-13,
        ///6.05767857e-13,  8.57214573e-13,  1.05500828e-12,  1.01908401e-12,
        ///4.20654157e-13, -1.27181504e-12, -4.82624813e-12, -1.12171615e-11,
        ///-2.14613679e-11, -3.62158587e-11, -5.50067590e-11, -7.49524986e-11,
        ///-8.88898158e-11, -8.29501242e-11, -3.39188850e-11,  9.28044690e-11,
        ///3.43110052e-10,  7.69477940e-10,  1.41819465e-09,  2.30420657e-09,
        ///3.36928629e-09,  4.42071385e-09,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_morl {
            get {
                return ResourceManager.GetString("wavefun_morl", resourceCulture);
            }
        }
    }
}
