//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neuronic.TimeFrequency.Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neuronic.TimeFrequency.Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.016567,0.19075,-0.18787,0.11029,-0.062853,0.021135,-0.064468,0.047675,-0.10791,0.21474,-0.043233,-0.089909,0.056332,-0.11729,0.13947,-0.033376,-0.12983,0.11817,0.15847,-0.1658,-0.068614,0.028193,0.1084,-0.13734,0.24835,-0.29709,0.17529,-0.085733,0.060819,0.016167,-0.067088,0.10934,-0.13715,0.038791,0.053631,-0.11943,0.068148,0.085869,-0.11687,0.07918,-0.11786,0.085993,0.0053729,0.078453,-0.038753,-0.23165,0.29025,-0.14703,0.15972,-0.25324,0.19869,-0.17427,0.10507,0.034378,0.12168,-0.3339,0.33336,-0.13769, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cwt_bior2_6 {
            get {
                return ResourceManager.GetString("cwt_bior2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.26665,-0.1298,-0.14045,0.0031975,-0.091625,-0.015011,0.070128,0.10658,0.23582,0.038454,-0.29938,-0.052492,0.0073875,0.13031,0.094127,-0.11134,0.20801,0.24497,-0.28987,-0.29233,0.15342,0.24253,-0.014226,0.046999,-0.17428,-0.085909,0.14857,-0.020149,0.029484,-0.12276,-0.027718,-0.11589,-0.067578,0.12353,-0.054248,0.074851,0.18196,-0.1136,-0.056765,0.012394,0.090637,0.15974,-0.010453,-0.17688,-0.2696,0.25305,0.14863,-0.12293,-0.15767,0.019681,0.12631,0.087014,0.23119,-0.029567,-0.34371,0.060069,0.060803,-0.3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cwt_bior3_3 {
            get {
                return ResourceManager.GetString("cwt_bior3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.059897,-0.082622,-0.052399,0.083168,-0.10666,0.065365,-0.0049233,0.053273,0.033451,0.017948,-0.16062,0.080925,-0.0072389,0.018189,0.057908,-0.094082,0.12413,0.043736,-0.1573,-0.042123,0.12658,0.019524,-0.027571,0.002563,-0.014753,-0.08907,0.17447,-0.14445,0.095793,-0.09368,0.021704,-0.023627,-0.042267,0.098697,-0.074387,0.045377,0.070703,-0.095717,0.0095531,0.042139,-0.018181,0.088779,-0.075687,-0.023398,-0.080391,0.12759,0.040108,-0.14931,0.078357,-0.069661,0.13924,-0.089517,0.15808,-0.11759,-0.061127,0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cwt_db10 {
            get {
                return ResourceManager.GetString("cwt_db10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0015877,-0.019058,-0.07243,0.11512,-0.14626,0.10976,-0.094776,0.09735,-0.012492,0.085465,-0.19211,0.12322,-0.073831,0.055199,0.028148,-0.12314,0.15084,0.02927,-0.10496,-0.069722,0.10583,0.0036785,0.0011034,-0.0095748,0.017912,-0.13604,0.233,-0.23018,0.21807,-0.1946,0.12919,-0.087775,-0.014076,0.091995,-0.11194,0.075536,0.042013,-0.073598,0.0082272,0.015275,-0.030017,0.11772,-0.089787,0.034516,-0.14396,0.15516,0.029282,-0.13877,0.1156,-0.16608,0.22128,-0.22011,0.29258,-0.21723,0.057769,-0.061286,0.18233,-0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cwt_db20 {
            get {
                return ResourceManager.GetString("cwt_db20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.075874,0.086033,0.024101,-0.0041041,0.022674,0.0018186,-0.034804,-0.029152,-0.080858,0.030835,0.10289,-0.012949,-0.010339,-0.05364,-0.006144,0.039413,-0.092504,-0.055076,0.13937,0.062602,-0.090967,-0.071078,0.037826,-0.023236,0.083827,-0.013601,-0.041854,0.0071336,0.0018645,0.042207,-0.0024851,0.045226,-9.0913e-05,-0.043116,0.029838,-0.039402,-0.049678,0.061566,0.0032468,-0.006424,-0.043663,-0.03734,0.019305,0.073307,0.067595,-0.13127,-0.0064544,0.047935,0.060538,-0.049055,-0.024439,-0.039605,-0.057126,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cwt_db5 {
            get {
                return ResourceManager.GetString("cwt_db5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.40979,-0.1896,0.37505,0.026934,0.14304,0.067999,-0.020167,-0.20423,-0.26058,-0.36235,0.32323,0.34025,-0.0061694,-0.06559,-0.29372,0.06889,-0.057911,-0.49496,0.023985,0.64031,0.098173,-0.39106,-0.24273,0.05478,-0.0176,0.42593,-0.21669,-0.02746,-0.059659,0.10059,0.16904,0.072681,0.25282,-0.10818,-0.070208,0.037433,-0.29714,-0.071611,0.22409,-0.026437,-0.026905,-0.30002,-0.10899,0.14673,0.44564,0.087081,-0.54448,0.12464,0.14764,0.27173,-0.289,-0.070181,-0.38945,-0.15833,0.3046,0.42138,-0.33222,0.40032,0.206 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cwt_gaus1 {
            get {
                return ResourceManager.GetString("cwt_gaus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.022167,-0.1872,0.35854,-0.32233,0.20117,-0.11449,0.10162,-0.13036,0.20588,-0.30911,0.22907,0.0072808,-0.14792,0.20997,-0.24952,0.14617,0.084705,-0.17341,-0.050117,0.24321,-0.11263,-0.020839,-0.089739,0.2717,-0.44097,0.55829,-0.49468,0.31336,-0.16539,0.041902,0.087598,-0.19403,0.24425,-0.16667,-0.012365,0.16227,-0.1574,-0.018873,0.18342,-0.22227,0.22284,-0.1967,0.1167,-0.095614,0.045583,0.22755,-0.48957,0.47776,-0.40045,0.44859,-0.47897,0.41358,-0.2832,0.12937,-0.18452,0.48032,-0.65248,0.47404,-0.13269,-0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cwt_gaus5 {
            get {
                return ResourceManager.GetString("cwt_gaus5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -3.3124e-17,6.7951e-17,-3.2041e-17,2.8983e-17,-4.952e-18,8.6233e-18,-2.6126e-17,8.6197e-19,-6.113e-17,5.0137e-17,2.8211e-17,-1.7003e-17,1.574e-17,-4.875e-17,2.3971e-17,7.8716e-18,-6.0938e-17,-4.0626e-18,7.9274e-17,-3.7781e-18,-3.6695e-17,-2.5593e-17,3.1774e-17,-4.5624e-17,9.0535e-17,-6.78e-17,2.7669e-17,-2.0581e-17,1.143e-17,2.0785e-17,-1.5557e-17,4.4906e-17,-2.6889e-17,-6.6383e-18,2.2529e-17,-4.0821e-17,-7.2932e-18,3.8047e-17,-2.3983e-17,2.0902e-17,-4.2908e-17,1.674e-18,9.683e-19,4.2627e-17,2.874e-17,-9.57 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cwt_haar {
            get {
                return ResourceManager.GetString("cwt_haar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.042281,0.46313,0.15171,-0.12144,0.0058256,-0.10838,-0.17846,-0.15908,-0.074925,0.3644,0.42229,-0.17959,-0.26189,-0.18164,0.072401,0.11787,-0.31102,0.075862,0.66602,0.046822,-0.6096,-0.22687,0.25437,0.16667,0.21962,-0.1194,-0.26652,0.078552,0.088895,0.14163,-0.0034978,0.039529,-0.11612,-0.19204,0.059452,-0.13068,-0.04971,0.30142,0.036513,-0.15527,-0.17425,-0.039419,0.28369,0.33687,-0.051459,-0.57811,0.010122,0.40746,0.097588,-0.26196,-0.22604,-0.07719,-0.023264,0.42602,0.34193,-0.34247,-0.017664,0.27849,- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cwt_mexh {
            get {
                return ResourceManager.GetString("cwt_mexh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.035217,-0.12198,-0.0041983,0.045661,-0.029337,0.022648,0.025754,0.012006,0.040176,-0.061101,-0.1042,0.075231,0.020542,0.037,-0.012395,-0.063414,0.099616,0.012495,-0.16642,-0.0019731,0.13974,0.027178,-0.078996,0.017037,-0.066553,0.026514,0.072938,-0.051269,0.013525,-0.045113,0.028141,-0.026628,0.014788,0.058236,-0.054592,0.039461,0.033385,-0.090796,0.015915,0.022569,0.024131,0.021756,-0.051959,-0.053581,-0.026876,0.16075,-0.030107,-0.086831,-0.010159,0.05488,0.032821,-0.011993,0.045111,-0.081391,-0.096185, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cwt_morl {
            get {
                return ResourceManager.GetString("cwt_morl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.11278,-0.065653,-0.049647,0.017068,-0.03823,-0.0049148,0.024252,0.023225,0.091127,0.0202,-0.12685,-0.00059191,-0.0034563,0.049036,0.038857,-0.068779,0.079871,0.10991,-0.12107,-0.11389,0.068938,0.093659,-0.027834,0.035328,-0.073458,-0.033207,0.070013,-0.02139,0.023007,-0.053347,0.0057781,-0.043625,-0.029056,0.061625,-0.037765,0.023557,0.080494,-0.058175,-0.015726,0.0023208,0.027055,0.061974,-0.0035048,-0.055087,-0.12125,0.11824,0.051756,-0.050298,-0.060945,0.012208,0.045363,0.012599,0.094036,-0.0039608,-0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cwt_rbio1_5 {
            get {
                return ResourceManager.GetString("cwt_rbio1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.053818,0.045868,0.012292,-0.040224,0.019865,-0.0015819,-0.00022354,0.025485,-0.024667,-0.02206,0.063342,-0.036462,0.010926,-0.0091039,-0.020845,0.072548,-0.021156,-0.066271,0.052319,0.04132,-0.040141,-0.029351,0.049311,-0.039388,0.026988,0.019343,-0.052813,0.036791,-0.031698,0.027964,-0.031775,0.0079085,0.018625,-0.04779,0.043101,0.0061482,-0.046695,0.044125,-0.0037882,0.00084847,0.010585,-0.022515,0.0011653,-0.010343,0.070998,-0.070687,-0.01347,0.027425,0.012965,-0.0051471,-0.014512,0.042709,-0.041974,- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cwt_rbio3_3 {
            get {
                return ResourceManager.GetString("cwt_rbio3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.8886e-21
        ///0
        ///.
        /// </summary>
        internal static string wavefun_bior2_6 {
            get {
                return ResourceManager.GetString("wavefun_bior2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.2446e-11
        ///0
        ///.
        /// </summary>
        internal static string wavefun_bior3_3 {
            get {
                return ResourceManager.GetString("wavefun_bior3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,-2.8977e-18,-2.0445e-17,-7.7725e-17,-2.1905e-16,-5.1242e-16,-1.049e-15,-1.9497e-15,-3.3743e-15,-5.5219e-15,-8.6319e-15,-1.2985e-14,-1.8897e-14,-2.6728e-14,-3.6898e-14,-4.9892e-14,-6.6261e-14,-8.6629e-14,-1.1168e-13,-1.4216e-13,-1.789e-13,-2.2276e-13,-2.7472e-13,-3.3579e-13,-4.0704e-13,-4.896e-13,-5.8469e-13,-6.9363e-13,-8.1784e-13,-9.5888e-13,-1.1184e-12,-1.2981e-12,-1.4999e-12,-1.7258e-12,-1.9779e-12,-2.2584e-12,-2.5696e-12,-2.9139e-12,-3.2939e-12,-3.7121e-12,-4.1713e-12,-4.6745e-12,-5.2245e-12,-5.8245e- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_db10 {
            get {
                return ResourceManager.GetString("wavefun_db10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,-1.025e-36,-1.3864e-35,-9.7214e-35,-4.7656e-34,-1.8458e-33,-6.0267e-33,-1.7259e-32,-4.4528e-32,-1.0551e-31,-2.3295e-31,-4.8449e-31,-9.5743e-31,-1.81e-30,-3.2912e-30,-5.7821e-30,-9.8513e-30,-1.6328e-29,-2.6399e-29,-4.1731e-29,-6.4628e-29,-9.8232e-29,-1.4677e-28,-2.1584e-28,-3.1283e-28,-4.4731e-28,-6.3164e-28,-8.8155e-28,-1.217e-27,-1.663e-27,-2.2507e-27,-3.0188e-27,-4.0146e-27,-5.2963e-27,-6.9341e-27,-9.0134e-27,-1.1636e-26,-1.4925e-26,-1.9026e-26,-2.4112e-26,-3.0387e-26,-3.8091e-26,-4.7505e-26,-5.8958e-26 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_db20 {
            get {
                return ResourceManager.GetString("wavefun_db20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,7.3777e-09,2.7825e-08,6.1202e-08,1.1132e-07,1.7592e-07,2.534e-07,3.4967e-07,4.6688e-07,5.9982e-07,7.4647e-07,9.0825e-07,1.0836e-06,1.2789e-06,1.4994e-06,1.7418e-06,2.0076e-06,2.2918e-06,2.5893e-06,2.903e-06,3.2316e-06,3.5763e-06,3.9392e-06,4.3168e-06,4.708e-06,5.1211e-06,5.5609e-06,6.0269e-06,6.5226e-06,7.0431e-06,7.5847e-06,8.1529e-06,8.7484e-06,9.3642e-06,9.9967e-06,1.0645e-05,1.1306e-05,1.1985e-05,1.2684e-05,1.3399e-05,1.4129e-05,1.4877e-05,1.5644e-05,1.6431e-05,1.7239e-05,1.8063e-05,1.8901e-05,1.9755e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_db5 {
            get {
                return ResourceManager.GetString("wavefun_db5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.24053203e-10,  1.81899706e-10,  2.65884545e-10,  3.87427851e-10,
        ///5.62762029e-10,  8.14881546e-10,  1.17624952e-09,  1.69254117e-09,
        ///2.42780238e-09,  3.47153250e-09,  4.94837305e-09,  7.03131242e-09,
        ///9.95961568e-09,  1.40630795e-08,  1.97947208e-08,  2.77746655e-08,
        ///3.88488529e-08,  5.41672581e-08,  7.52877223e-08,  1.04313247e-07,
        ///1.44072835e-07,  1.98358758e-07,  2.72236648e-07,  3.72449161e-07,
        ///5.07939354e-07,  6.90526586e-07,  9.35775844e-07,  1.26411132e-06,
        ///1.70223704e-06,  2.28494160e-06,  3. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_gaus1 {
            get {
                return ResourceManager.GetString("wavefun_gaus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -7.01897073e-10, -1.02079158e-09, -1.47981439e-09, -2.13837049e-09,
        ///-3.08008844e-09, -4.42228694e-09, -6.32897073e-09, -9.02860395e-09,
        ///-1.28383244e-08, -1.81968062e-08, -2.57086866e-08, -3.62043948e-08,
        ///-5.08204057e-08, -7.11064688e-08, -9.91683126e-08, -1.37856803e-07,
        ///-1.91017672e-07, -2.63819879e-07, -3.63185603e-07, -4.98351007e-07,
        ///-6.81594515e-07, -9.29178682e-07, -1.26256316e-06, -1.70996012e-06,
        ///-2.30832023e-06, -3.10585729e-06, -4.16524344e-06, -5.56763515e-06,
        ///-7.41772273e-06, -9.85003485e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_gaus2 {
            get {
                return ResourceManager.GetString("wavefun_gaus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -3.01085754e-09, -4.34144868e-09, -6.23951610e-09, -8.93793604e-09,
        ///-1.27612126e-08, -1.81598911e-08, -2.57572385e-08, -3.64123110e-08,
        ///-5.13048158e-08, -7.20488368e-08, -1.00844614e-07, -1.40680277e-07,
        ///-1.95598857e-07, -2.71050205e-07, -3.74352877e-07, -5.15297712e-07,
        ///-7.06933197e-07, -9.66582879e-07, -1.31715757e-06, -1.78884017e-06,
        ///-2.42123915e-06, -3.26612832e-06, -4.39091643e-06, -5.88302006e-06,
        ///-7.85534852e-06, -1.04531499e-05, -1.38625137e-05, -1.83208765e-05,
        ///-2.41299365e-05, -3.16714437e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_gaus3 {
            get {
                return ResourceManager.GetString("wavefun_gaus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.06681183e-08,  1.52451629e-08,  2.17124166e-08,  3.08186435e-08,
        ///4.35958827e-08,  6.14612353e-08,  8.63531353e-08,  1.20913008e-07,
        ///1.68726388e-07,  2.34641558e-07,  3.25188795e-07,  4.49129502e-07,
        ///6.18172259e-07,  8.47902239e-07,  1.15898199e-06,  1.57869558e-06,
        ///2.14292473e-06,  2.89866571e-06,  3.90721904e-06,  5.24821173e-06,
        ///7.02464333e-06,  9.36918356e-06,  1.24519899e-05,  1.64903592e-05,
        ///2.17605764e-05,  2.86123782e-05,  3.74865015e-05,  4.89358472e-05,
        ///6.36508400e-05,  8.24896165e-05,  1. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_gaus4 {
            get {
                return ResourceManager.GetString("wavefun_gaus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.25257351e-08,  4.60428744e-08,  6.49505911e-08,  9.13030705e-08,
        ///1.27898469e-07,  1.78533186e-07,  2.48337338e-07,  3.44215331e-07,
        ///4.75421720e-07,  6.54310347e-07,  8.97304153e-07,  1.22614452e-06,
        ///1.66949269e-06,  2.26497194e-06,  3.06175851e-06,  4.12385102e-06,
        ///5.53417393e-06,  7.39969919e-06,  9.85780212e-06,  1.30841028e-05,
        ///1.73020820e-05,  2.27947985e-05,  2.99190764e-05,  3.91225655e-05,
        ///5.09641127e-05,  6.61379084e-05,  8.55018838e-05,  1.10110832e-04,
        ///1.41254698e-04,  1.80502426e-04,  2. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_gaus5 {
            get {
                return ResourceManager.GetString("wavefun_gaus5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_haar {
            get {
                return ResourceManager.GetString("wavefun_haar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -6.91988742e-13, -1.12277873e-12, -1.81435638e-12, -2.92000322e-12,
        ///-4.68031839e-12, -7.47132786e-12, -1.18781687e-11, -1.88074286e-11,
        ///-2.96576342e-11, -4.65767972e-11, -7.28496762e-11, -1.13477390e-10,
        ///-1.76040887e-10, -2.71981278e-10, -4.18489381e-10, -6.41281230e-10,
        ///-9.78655663e-10, -1.48739803e-09, -2.25132897e-09, -3.39362387e-09,
        ///-5.09448066e-09, -7.61633480e-09, -1.13396699e-08, -1.68136270e-08,
        ///-2.48271744e-08, -3.65086937e-08, -5.34646309e-08, -7.79715632e-08,
        ///-1.13240908e-07, -1.63781882e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_mexh {
            get {
                return ResourceManager.GetString("wavefun_mexh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -8.44621402e-15, -8.44451069e-15, -3.51327382e-15,  1.17518329e-14,
        ///4.57902859e-14,  1.10299978e-13,  2.19073416e-13,  3.83962177e-13,
        ///6.05767857e-13,  8.57214573e-13,  1.05500828e-12,  1.01908401e-12,
        ///4.20654157e-13, -1.27181504e-12, -4.82624813e-12, -1.12171615e-11,
        ///-2.14613679e-11, -3.62158587e-11, -5.50067590e-11, -7.49524986e-11,
        ///-8.88898158e-11, -8.29501242e-11, -3.39188850e-11,  9.28044690e-11,
        ///3.43110052e-10,  7.69477940e-10,  1.41819465e-09,  2.30420657e-09,
        ///3.36928629e-09,  4.42071385e-09,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wavefun_morl {
            get {
                return ResourceManager.GetString("wavefun_morl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///0
        ///.
        /// </summary>
        internal static string wavefun_rbio1_5 {
            get {
                return ResourceManager.GetString("wavefun_rbio1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///0
        ///.
        /// </summary>
        internal static string wavefun_rbio3_3 {
            get {
                return ResourceManager.GetString("wavefun_rbio3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.0069053,0.013811,0.046956,-0.10772,-0.16987,0.44747,0.96675,0.44747,-0.16987,-0.10772,0.046956,0.013811,-0.0069053,0
        ///0,-0,0,-0,0,-0,0.35355,-0.70711,0.35355,-0,0,-0,0,-0
        ///0,0,0,0,0,0.35355,0.70711,0.35355,0,0,0,0,0,0
        ///0,0.0069053,0.013811,-0.046956,-0.10772,0.16987,0.44747,-0.96675,0.44747,0.16987,-0.10772,-0.046956,0.013811,0.0069053
        ///.
        /// </summary>
        internal static string wfilters_bior2_6 {
            get {
                return ResourceManager.GetString("wfilters_bior2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.066291,-0.19887,-0.15468,0.99437,0.99437,-0.15468,-0.19887,0.066291
        ///0,-0,0.17678,-0.53033,0.53033,-0.17678,0,-0
        ///0,0,0.17678,0.53033,0.53033,0.17678,0,0
        ///0.066291,0.19887,-0.15468,-0.99437,0.99437,0.15468,-0.19887,-0.066291
        ///.
        /// </summary>
        internal static string wfilters_bior3_3 {
            get {
                return ResourceManager.GetString("wfilters_bior3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.02667,0.18818,0.5272,0.68846,0.28117,-0.24985,-0.19595,0.12737,0.093057,-0.071394,-0.029458,0.033213,0.0036066,-0.010733,0.0013954,0.0019924,-0.00068586,-0.00011647,9.3589e-05,-1.3264e-05
        ///-1.3264e-05,-9.3589e-05,-0.00011647,0.00068586,0.0019924,-0.0013954,-0.010733,-0.0036066,0.033213,0.029458,-0.071394,-0.093057,0.12737,0.19595,-0.24985,-0.28117,0.68846,-0.5272,0.18818,-0.02667
        ///.
        /// </summary>
        internal static string wfilters_db10 {
            get {
                return ResourceManager.GetString("wfilters_db10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00077995,0.010549,0.063424,0.21994,0.4727,0.61049,0.3615,-0.13921,-0.32679,-0.016727,0.22829,0.03985,-0.15546,-0.024717,0.10229,0.0056322,-0.061723,0.0058747,0.032294,-0.0087893,-0.013811,0.0067216,0.0044205,-0.0035815,-0.00083156,0.0013926,-5.3498e-05,-0.0003851,0.00010153,6.7743e-05,-3.7106e-05,-4.3761e-06,7.2412e-06,-1.012e-06,-6.8471e-07,2.6339e-07,2.0143e-10,-1.8148e-08,4.0561e-09,-2.9988e-10
        ///-2.9988e-10,-4.0561e-09,-1.8148e-08,-2.0143e-10,2.6339e-07,6.8471e-07,-1.012e-06,-7.2412e-06,-4.3761e-06,3.71 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wfilters_db20 {
            get {
                return ResourceManager.GetString("wfilters_db20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.1601,0.60383,0.72431,0.13843,-0.24229,-0.032245,0.077571,-0.0062415,-0.012581,0.0033357
        ///0.0033357,0.012581,-0.0062415,-0.077571,-0.032245,0.24229,0.13843,-0.72431,0.60383,-0.1601
        ///.
        /// </summary>
        internal static string wfilters_db5 {
            get {
                return ResourceManager.GetString("wfilters_db5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.70711,0.70711
        ///0.70711,-0.70711
        ///.
        /// </summary>
        internal static string wfilters_haar {
            get {
                return ResourceManager.GetString("wfilters_haar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,0,0,0,0.70711,0.70711,0,0,0,0
        ///0.016573,0.016573,-0.12153,-0.12153,0.70711,-0.70711,0.12153,0.12153,-0.016573,-0.016573
        ///0.016573,-0.016573,-0.12153,0.12153,0.70711,0.70711,0.12153,-0.12153,-0.016573,0.016573
        ///0,-0,0,-0,0.70711,-0.70711,0,-0,0,-0
        ///.
        /// </summary>
        internal static string wfilters_rbio1_5 {
            get {
                return ResourceManager.GetString("wfilters_rbio1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,0,0.17678,0.53033,0.53033,0.17678,0,0
        ///0.066291,0.19887,-0.15468,-0.99437,0.99437,0.15468,-0.19887,-0.066291
        ///0.066291,-0.19887,-0.15468,0.99437,0.99437,-0.15468,-0.19887,0.066291
        ///0,-0,0.17678,-0.53033,0.53033,-0.17678,0,-0
        ///.
        /// </summary>
        internal static string wfilters_rbio3_3 {
            get {
                return ResourceManager.GetString("wfilters_rbio3_3", resourceCulture);
            }
        }
    }
}
